In [68]:
import pandas as pd
import numpy as np
import matplotlib as plot
import openpyxl

In [69]:

df1= pd.read_csv('IEA_Global_EV_2030_Projections_Data_2023.csv')
df2= pd.read_excel('StatePopulations.xlsx')
df3= pd.read_csv('state_totals.csv')
df4= pd.read_excel('ev-registration-counts-by-state_6-30-22(altered).xlsx')
df5= pd.read_csv('alt_fuel_stations(Nov-3-2023).csv')

C:\Users\artif\AppData\Local\Temp\ipykernel_21384\2720100684.py:5: DtypeWarning: Columns (6,16,20,25,31,33,36,43,46,52,53,57,58,60,62,65,67,69,71) have mixed types. Specify dtype option on import or set low_memory=False.
  df5= pd.read_csv('alt_fuel_stations(Nov-3-2023).csv')

In [70]:
#Code to clean df4
df4.drop(['Unnamed: 0', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace= True)
df4.rename(columns={'Unnamed: 1': 'state', 'Unnamed: 2': 'registration'}, inplace=True)

In [71]:
df4.reset_index(drop=True, inplace=True)

In [72]:
pd.set_option("display.max_columns", 80)

In [73]:
df5.drop(['LNG Station Sells Renewable Natural Gas','CNG Station Sells Renewable Natural Gas','RD Maximum Biodiesel Level', 'RD Blended with Biodiesel', 'RD Blends (French)', 'RD Blends','LNG Vehicle Class','CNG Vehicle Class','CNG PSI', 'CNG Fill Type Code', 'Hydrogen Standards', 'Hydrogen Pressures', 'LPG Nozzle Types', 'E85 Other Ethanol Blends', 'LNG On-Site Renewable Source'], axis = 1, inplace= True)

In [74]:
df5

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,Expected Date,Groups With Access Code,Access Days Time,Cards Accepted,BD Blends,NG Fill Type Code,NG PSI,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,EV Other Info,EV Network,EV Network Web,Geocode Status,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Owner Type Code,Federal Agency ID,Federal Agency Name,Open Date,Hydrogen Status Link,NG Vehicle Class,LPG Primary,E85 Blender Pump,EV Connector Types,Country,Intersection Directions (French),Access Days Time (French),BD Blends (French),Groups With Access Code (French),Hydrogen Is Retail,Access Code,Access Detail Code,Federal Agency Code,Facility Type,CNG Dispenser Num,CNG On-Site Renewable Source,CNG Total Compression Capacity,CNG Storage Capacity,EV Pricing,EV Pricing (French),EV On-Site Renewable Source,Restricted Access,NPS Unit Name,Maximum Vehicle Class,EV Workplace Charging
0,CNG,Spire - Montgomery Operations Center,2951 Chestnut St,NaN,Montgomery,AL,36107.0,NaN,NaN,E,NaN,Private,NaN,NaN,NaN,B,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,32.367916,-86.267021,2023-04-06,17,2023-05-30 18:46:28 UTC,T,NaN,NaN,2010-12-01,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé,NaN,private,NaN,NaN,STANDALONE_STATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MD,NaN
1,CNG,Metropolitan Atlanta Rapid Transit Authority,2424 Piedmont Rd NE,NaN,Atlanta,GA,30324.0,NaN,NaN,E,NaN,Private - Government only,NaN,NaN,NaN,Q,3000,NaN,NaN,NaN,NaN,NaN,NaN,200-8,33.821911,-84.367461,2023-01-10,45,2023-08-01 22:53:06 UTC,LG,NaN,NaN,1996-12-15,NaN,LD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé - Réservé au gouvernement,NaN,private,GOVERNMENT,NaN,FLEET_GARAGE,NaN,NaN,30.0,NaN,NaN,NaN,NaN,NaN,NaN,LD,NaN
2,CNG,United Parcel Service,270 Marvin Miller Dr,NaN,Atlanta,GA,30336.0,NaN,NaN,E,NaN,Private,NaN,NaN,NaN,B,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,33.760256,-84.543822,2022-06-14,64,2023-08-03 03:41:49 UTC,P,NaN,NaN,1997-01-01,NaN,HD,NaN,NaN,NaN,US,NaN,NaN,NaN,Privé,NaN,private,NaN,NaN,STANDALONE_STATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HD,NaN
3,CNG,Arkansas Oklahoma Gas Corp,2100 S Waldron Rd,NaN,Fort Smith,AR,72903.0,NaN,479-783-3181,E,NaN,Public - Credit card at all times,24 hours daily,FuelMan M V Wright_Exp,NaN,Q,3600,NaN,NaN,NaN,NaN,NaN,NaN,200-9,35.362213,-94.375338,2023-08-10,73,2023-08-10 16:58:49 UTC,T,NaN,NaN,1997-01-01,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Public - Carte de crédit en tout temps,NaN,public,CREDIT_CARD_ALWAYS,NaN,UTILITY,1.0,NaN,250.0,57855.0,NaN,NaN,NaN,False,NaN,MD,NaN
4,CNG,Clean Energy - Logan International Airport,1000 Cottage St Ext,"From Route 1, take the first exit after Callah...",East Boston,MA,2128.0,NaN,866-809-4869,E,NaN,Public - Credit card at all times,24 hours daily; call 866-809-4869 for Clean En...,A CleanEnergy Comdata D FuelMan M V Voyager Wr...,NaN,Q,3000 3600,NaN,NaN,NaN,NaN,NaN,NaN,GPS,42.374706,-71.026549,2023-09-14,81,2023-09-14 14:01:49 UTC,SG,NaN,NaN,1996-11-15,NaN,MD,NaN,NaN,NaN,US,NaN,NaN,NaN,Public - Carte de crédit en tout temps,NaN,public,CREDIT_CARD_ALWAYS,NaN,AIRPORT,4.0,NONE,850.0,NaN,NaN,NaN,NaN,False,NaN,MD,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78368,ELEC,12102 S. Elk Creek Road (US-45Y-J5H-1),12102 S. Elk Creek Road,NaN,Pine,CO,80470,NaN,866-576-1495,E,NaN,Public,24 hours daily,A ACCOUNT_BALANCE D M V,NaN,NaN,NaN,NaN,1.0,NaN,NaN,RIVIAN_WAYPOINTS,https://rivian.com/experience/charging,GPS,39.497179,-105.381857,2023-11-03,316632,2023-11-03 01:05:40 UTC,NaN,NaN,NaN,2023-11-02,NaN,NaN,NaN,NaN,J1772,US,NaN,NaN,NaN,Public,NaN,public,NaN,NaN,PUBLIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
78369,ELEC,Hecht Warehouse Garage,1474 Okie St. NE.,NaN,Washington,DC,20002,NaN,855-223-5351,E,NaN,Public,24 hours daily,A D M V,NaN,NaN,NaN,NaN,3.0,NaN,NaN,FLASH,https://www.flashparking.com/products/diversif...,GPS,38.915291,-76.982678,2023-11-03,316633,2023-11-03 01:06:03 UTC,NaN,NaN,NaN,2023-11-03,NaN,NaN,NaN,NaN,J1772,US,NaN,NaN,NaN,Public,NaN,public,NaN,NaN,PUBLIC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
78370,ELEC,Tower Square Garage,1500 Main Street,NaN,Springfield,MA,1115,NaN,888-356-8911,E,NaN,Public,24 hours daily,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,FLO,https://flo.ca/,GPS,42.102809,-72.591733,2023-11-03,316634,2023-11-03 01:09:05 UTC,NaN,NaN,NaN,2023-11-03,NaN,NaN,NaN,NaN,J1772,US,NaN,NaN,NaN,Public,NaN,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
78371,ELEC,The House by the Side of the Road,370 Gibbons Hwy,NaN,Wilton,NH,3086,NaN,888-356-8911,E,NaN,Public,24 hours daily,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,FLO,https://flo.ca/,GPS,42.830470,-71.751223,2023-11-03,316635,2023-11-03 01:09:05 UTC,NaN,NaN,NaN,2023-11-03,NaN,NaN,NaN,NaN,J1772,US,NaN,NaN,NaN,Public,NaN,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
78372,ELEC,Bill Luke Santan,3404 S Speedway Dr,NaN,Gilbert,AZ,85297,NaN,480-676-6699,E,NaN,Private,Service use only,NaN,NaN,NaN,NaN,NaN,8.0,1.0,NaN,Non-Networked,NaN,GPS,33.287837,-111.763513,NaN,316639,2023-11-03 19:56:22 UTC,P,NaN,NaN,2023-11-03,NaN,NaN,NaN,NaN,J1772 J1772COMBO,US,NaN,NaN,NaN,Privé,NaN,private,NaN,NaN,CAR_DEALER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LD,False

In [75]:
df5.drop(['NG PSI', 'NG Fill Type Code','BD Blends','BD Blends (French)', 'CNG Dispenser Num', 'CNG On-Site Renewable Source', 'CNG Total Compression Capacity', 'CNG Storage Capacity'], axis = 1, inplace=True)
df5.drop(['Hydrogen Is Retail','Groups With Access Code (French)', 'Access Days Time (French)','Intersection Directions (French)'] ,axis = 1, inplace=True)
df5.drop(['E85 Blender Pump', 'LPG Primary', 'Hydrogen Status Link','EV Pricing (French)'], axis =1, inplace= True )
df5.drop(['NG Vehicle Class', ], axis=1, inplace= True)
df5 = df5.query('`Fuel Type Code` == "ELEC"')

In [76]:
df5['Facility Type'].value_counts()

Facility Type
HOTEL          2932
CAR_DEALER     2795
OFFICE_BLDG     903
PARKING_LOT     874
FED_GOV         864
               ...
PHARMACY          4
WORKPLACE         4
STORAGE           3
STADIUM           3
TNC               1
Name: count, Length: 63, dtype: int64

In [77]:
df5

,Fuel Type Code,Station Name,Street Address,Intersection Directions,City,State,ZIP,Plus4,Station Phone,Status Code,Expected Date,Groups With Access Code,Access Days Time,Cards Accepted,EV Level1 EVSE Num,EV Level2 EVSE Num,EV DC Fast Count,EV Other Info,EV Network,EV Network Web,Geocode Status,Latitude,Longitude,Date Last Confirmed,ID,Updated At,Owner Type Code,Federal Agency ID,Federal Agency Name,Open Date,EV Connector Types,Country,Access Code,Access Detail Code,Federal Agency Code,Facility Type,EV Pricing,EV On-Site Renewable Source,Restricted Access,NPS Unit Name,Maximum Vehicle Class,EV Workplace Charging
130,ELEC,LADWP - Truesdale Center,11797 Truesdale St,NaN,Sun Valley,C@,91352.0,NaN,NaN,E,NaN,Private,Fleet use only,NaN,NaN,57.0,2.0,NaN,SHELL_RECHARGE,https://shellrecharge.com/en-us/solutions,GPS,34.248319,-118.387971,2023-09-14,1517,2023-09-14 14:01:49 UTC,LG,NaN,NaN,1999-10-15,CHADEMO J1772 J1772COMBO,US,private,NaN,NaN,UTILITY,NaN,NaN,NaN,NaN,NaN,True
131,ELEC,LADWP - West LA District Office,1394 S Sepulveda Blvd,NaN,Los Angeles,C@,90024.0,NaN,NaN,E,NaN,Private,NaN,NaN,NaN,4.0,NaN,NaN,Non-Networked,NaN,200-8,34.052542,-118.448504,2023-01-10,1519,2023-02-15 22:45:41 UTC,LG,NaN,NaN,2020-02-28,J1772,US,private,NaN,NaN,UTILITY,Free,NaN,NaN,NaN,NaN,True
132,ELEC,Los Angeles Convention Center,1201 S Figueroa St,West hall and South hall,Los Angeles,C@,90015.0,NaN,213-741-1151,E,NaN,Public,5:30am-9pm; pay lot,NaN,NaN,7.0,NaN,NaN,Non-Networked,NaN,GPS,34.040539,-118.271387,2023-01-10,1523,2023-02-14 15:54:11 UTC,P,NaN,NaN,1995-08-30,J1772,US,public,NaN,NaN,PARKING_GARAGE,Free; parking fee,NaN,False,NaN,LD,False
133,ELEC,LADWP - John Ferraro Building,111 N Hope St,Across Hope,Los Angeles,C@,90012.0,NaN,NaN,E,NaN,Private,For fleet and employee use only,NaN,NaN,338.0,12.0,NaN,Non-Networked,NaN,GPS,34.059133,-118.248589,2023-09-14,1525,2023-09-14 14:01:49 UTC,LG,NaN,NaN,1999-10-15,CHADEMO J1772 J1772COMBO,US,private,NaN,NaN,UTILITY,NaN,NaN,NaN,NaN,LD,True
134,ELEC,LADWP - Haynes Power Plant,6801 E 2nd St,NaN,Long Beach,C@,90803.0,NaN,NaN,E,NaN,Private,Fleet use only,NaN,NaN,19.0,1.0,NaN,Non-Networked,NaN,GPS,33.759802,-118.096665,2023-01-10,1531,2023-02-15 22:45:41 UTC,LG,NaN,NaN,2018-05-01,CHADEMO J1772 J1772COMBO,US,private,NaN,NaN,UTILITY,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78368,ELEC,12102 S. Elk Creek Road (US-45Y-J5H-1),12102 S. Elk Creek Road,NaN,Pine,CO,80470,NaN,866-576-1495,E,NaN,Public,24 hours daily,A ACCOUNT_BALANCE D M V,NaN,1.0,NaN,NaN,RIVIAN_WAYPOINTS,https://rivian.com/experience/charging,GPS,39.497179,-105.381857,2023-11-03,316632,2023-11-03 01:05:40 UTC,NaN,NaN,NaN,2023-11-02,J1772,US,public,NaN,NaN,PUBLIC,NaN,NaN,NaN,NaN,NaN,False
78369,ELEC,Hecht Warehouse Garage,1474 Okie St. NE.,NaN,Washington,DC,20002,NaN,855-223-5351,E,NaN,Public,24 hours daily,A D M V,NaN,3.0,NaN,NaN,FLASH,https://www.flashparking.com/products/diversif...,GPS,38.915291,-76.982678,2023-11-03,316633,2023-11-03 01:06:03 UTC,NaN,NaN,NaN,2023-11-03,J1772,US,public,NaN,NaN,PUBLIC,NaN,NaN,NaN,NaN,NaN,False
78370,ELEC,Tower Square Garage,1500 Main Street,NaN,Springfield,MA,1115,NaN,888-356-8911,E,NaN,Public,24 hours daily,NaN,NaN,12.0,NaN,NaN,FLO,https://flo.ca/,GPS,42.102809,-72.591733,2023-11-03,316634,2023-11-03 01:09:05 UTC,NaN,NaN,NaN,2023-11-03,J1772,US,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
78371,ELEC,The House by the Side of the Road,370 Gibbons Hwy,NaN,Wilton,NH,3086,NaN,888-356-8911,E,NaN,Public,24 hours daily,NaN,NaN,2.0,NaN,NaN,FLO,https://flo.ca/,GPS,42.830470,-71.751223,2023-11-03,316635,2023-11-03 01:09:05 UTC,NaN,NaN,NaN,2023-11-03,J1772,US,public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
78372,ELEC,Bill Luke Santan,3404 S Speedway Dr,NaN,Gilbert,AZ,85297,NaN,480-676-6699,E,NaN,Private,Service use only,NaN,NaN,8.0,1.0,NaN,Non-Networked,NaN,GPS,33.287837,-111.763513,NaN,316639,2023-11-03 19:56:22 UTC,P,NaN,NaN,2023-11-03,J1772 J1772COMBO,US,private,NaN,NaN,CAR_DEALER,NaN,NaN,NaN,NaN,LD,False

In [78]:
df5['EV Network'].value_counts()

EV Network
ChargePoint Network    35260
Non-Networked           9441
Blink Network           6316
Tesla Destination       4205
Tesla                   1997
Volta                   1464
EV Connect              1294
SHELL_RECHARGE          1178
eVgo Network             967
Electrify America        925
FLO                      736
AMPUP                    639
RIVIAN_ADVENTURE         340
RIVIAN_WAYPOINTS         326
LIVINGSTON               292
OpConnect                219
CHARGEUP                 191
FCN                      151
EVCS                     148
POWERFLEX                143
UNIVERSAL                122
ZEFNET                   108
GRAVITI_ENERGY           103
SWTCH                     94
EVGATEWAY                 78
RED_E                     59
CHARGELAB                 58
FLASH                     54
EVRANGE                   38
EVMATCH                   34
CIRCLE_K                  22
7CHARGE                   22
FPLEV                     19
NOODOE                    15
WAVE                       6
JULE                       6
AMPED_UP                   3
CHARGIE                    3
LOOP                       2
REVEL                      2
POWER_NODE                 1
Name: count, dtype: int64

In [79]:
projections = df1.query("category == 'Projection-STEPS' or category == 'Projection-APS'")

In [80]:
projections

,region,category,parameter,mode,powertrain,year,unit,value
1331,China,Projection-STEPS,EV charging points,EV,Publicly available fast,2020,charging points,310000.0
1332,China,Projection-STEPS,EV charging points,EV,Publicly available slow,2020,charging points,500000.0
1335,China,Projection-STEPS,EV sales,Buses,BEV,2020,Vehicles,62000.0
1336,China,Projection-STEPS,EV stock,Buses,BEV,2020,Vehicles,480000.0
1337,China,Projection-STEPS,EV sales,Buses,PHEV,2020,Vehicles,3600.0
...,...,...,...,...,...,...,...,...
9537,World,Projection-APS,EV stock,Trucks,PHEV,2030,Vehicles,910000.0
9538,World,Projection-APS,EV stock,Vans,BEV,2030,Vehicles,12000000.0
9539,World,Projection-APS,EV stock,Vans,PHEV,2030,Vehicles,1300000.0
9540,World,Projection-APS,EV stock,Cars,BEV,2030,Vehicles,180000000.0
9541,World,Projection-APS,EV stock,Cars,PHEV,2030,Vehicles,50000000.0

In [81]:
df4

                                      state        registration
0   Electric Vehicle Registrations by State                 NaN
1                                     State  Registration Count
2                                   Alabama                4750
3                                    Alaska                1290
4                                   Arizona               40740
5                                  Arkansas                2390
6                                California              563070
7                                  Colorado               37000
8                               Connecticut               13350
9                                  Delaware                3010
10                     District of Columbia                3700
11                                  Florida               95640
12                                  Georgia               34020
13                                   Hawaii               14220
14                                    Idaho                3500
15                                 Illinois               36520
16                                  Indiana               10360
17                                     Iowa                3660
18                                   Kansas                4500
19                                 Kentucky                4220
20                                Louisiana                3180
21                                    Maine                3040
22                                 Maryland               25630
23                            Massachusetts               30470
24                                 Michigan               17460
25                                Minnesota               15000
26                              Mississippi                1310
27                                 Missouri               10050
28                                  Montana                1650
29                                 Nebraska                2710
30                                   Nevada               17380
31                            New Hampshire                4000
32                               New Jersey               47830
33                               New Mexico                4150
34                                 New York               51870
35                           North Carolina               25190
36                             North Dakota                 380
37                                     Ohio               21200
38                                 Oklahoma                7080
39                                   Oregon               30290
40                             Pennsylvania               26770
41                             Rhode Island                2550
42                           South Carolina                7440
43                             South Dakota                 680
44                                Tennessee               12160
45                                    Texas               80900
46                                     Utah               16480
47                                  Vermont                3370
48                                 Virginia               30660
49                               Washington               66810
50                            West Virginia                1010
51                                Wisconsin                9330
52                                  Wyoming                 510
53                                    Total             1454480

In [82]:
projections.query("region == 'USA' or region == 'rest of the world'")

,region,category,parameter,mode,powertrain,year,unit,value
8483,USA,Projection-STEPS,Electricity demand,Cars,EV,2020,GWh,5400.0
8484,USA,Projection-STEPS,EV charging points,EV,Publicly available fast,2020,charging points,17000.0
8485,USA,Projection-STEPS,EV charging points,EV,Publicly available slow,2020,charging points,82000.0
8488,USA,Projection-APS,EV sales,Cars,BEV,2020,Vehicles,230000.0
8489,USA,Projection-APS,EV stock,Cars,BEV,2020,Vehicles,1100000.0
...,...,...,...,...,...,...,...,...
8715,USA,Projection-APS,EV stock share,Trucks,EV,2030,percent,4.0
8716,USA,Projection-APS,EV sales share,Cars,EV,2030,percent,50.0
8717,USA,Projection-APS,EV sales share,Trucks,EV,2030,percent,28.0
8718,USA,Projection-APS,EV stock share,Vans,EV,2030,percent,13.0
8719,USA,Projection-APS,EV stock share,Cars,EV,2030,percent,16.0

In [83]:
projections['region'].value_counts()

region
China                370
Europe               370
World                370
Rest of the world    364
India                281
USA                  208
Name: count, dtype: int64

In [84]:
df2

                    State   Population
0                Alabama     4,817,678
1                 Alaska       728,300
2                Arizona     6,561,516
3               Arkansas     2,947,036
4             California    38,066,920
5               Colorado     5,197,580
6            Connecticut     3,592,053
7               Delaware       917,060
8   District of Columbia       633,736
9                Florida    19,361,792
10               Georgia     9,907,756
11                Hawaii     1,392,704
12                 Idaho     1,599,464
13              Illinois    12,868,747
14               Indiana     6,542,411
15                  Iowa     3,078,116
16                Kansas     2,882,946
17              Kentucky     4,383,272
18             Louisiana     4,601,049
19                 Maine     1,328,535
20              Maryland     5,887,776
21         Massachusetts     6,657,291
22              Michigan     9,889,024
23             Minnesota     5,383,661
24           Mississippi     2,984,345
25              Missouri     6,028,076
26               Montana     1,006,370
27              Nebraska     1,855,617
28                Nevada     2,761,584
29         New Hampshire     1,321,069
30            New Jersey     8,874,374
31            New Mexico     2,080,085
32              New York    19,594,330
33        North Carolina     9,750,405
34          North Dakota       704,925
35                  Ohio    11,560,380
36              Oklahoma     3,818,851
37                Oregon     3,900,343
38          Pennsylvania    12,758,729
39          Rhode Island     1,053,252
40        South Carolina     4,727,273
41          South Dakota       834,708
42             Tennessee     6,451,365
43                 Texas    26,092,033
44                  Utah     2,858,111
45               Vermont       626,358
46              Virginia     8,185,131
47            Washington     6,899,123
48         West Virginia     1,853,881
49             Wisconsin     5,724,692
50               Wyoming       575,251

In [ ]:
test = df1['year'].value_counts()

In [ ]:
pd.set_option('display.max_rows', 100)

In [22]:
df4.shape

(53, 2)

In [ ]:
df3.shape

(66, 16)

In [86]:
df3

        Alabama (2)    5,463,966
0           Alaska       686,142
1           Arizona    6,064,542
2          Arkansas    3,555,142
3       California    31,349,073
4         Colorado     5,096,394
5   Connecticut (2)    2,756,485
6         Delaware       472,175
7    Dist. of Col.       363,287
8          Florida    19,180,165
9       Georgia (5)    9,142,656
10           Hawaii    1,235,473
11        Idaho (3)    1,976,199
12        Illinois    11,003,729
13      Indiana (4)    6,241,291
14            Iowa     3,839,312
15           Kansas    2,606,313
16         Kentucky    4,408,730
17    Louisiana (3)    3,862,490
18           Maine     1,387,656
19         Maryland    4,910,674
20   Massachusetts     5,207,052
21         Michigan    9,556,452
22       Minnesota     5,511,960
23     Mississippi     2,385,768
24     Missouri (2)    5,603,939
25         Montana     2,140,014
26         Nebraska    1,933,528
27       Nevada (2)    2,676,143
28    New Hampshire    1,417,949
29      New Jersey     6,249,905
30       New Mexico    1,862,673
31     New York (3)    9,408,796
32   North Carolina    8,707,506
33     North Dakota      925,186
34             Ohio   10,892,377
35       Oklahoma      3,353,167
36          Oregon     4,010,635
37     Pennsylvania   10,927,881
38    Rhode Island       801,654
39   South Carolina    5,091,679
40    South Dakota     1,433,044
41       Tennessee     6,712,722
42           Texas    23,012,990
43             Utah    2,838,505
44          Vermont      614,340
45         Virginia    7,652,036
46      Washington     7,966,147
47    West Virginia    1,219,024
48       Wisconsin     5,769,058
49         Wyoming       870,969
50              NaN  282,354,993

In [87]:
df2

                    State   Population
0                Alabama     4,817,678
1                 Alaska       728,300
2                Arizona     6,561,516
3               Arkansas     2,947,036
4             California    38,066,920
5               Colorado     5,197,580
6            Connecticut     3,592,053
7               Delaware       917,060
8   District of Columbia       633,736
9                Florida    19,361,792
10               Georgia     9,907,756
11                Hawaii     1,392,704
12                 Idaho     1,599,464
13              Illinois    12,868,747
14               Indiana     6,542,411
15                  Iowa     3,078,116
16                Kansas     2,882,946
17              Kentucky     4,383,272
18             Louisiana     4,601,049
19                 Maine     1,328,535
20              Maryland     5,887,776
21         Massachusetts     6,657,291
22              Michigan     9,889,024
23             Minnesota     5,383,661
24           Mississippi     2,984,345
25              Missouri     6,028,076
26               Montana     1,006,370
27              Nebraska     1,855,617
28                Nevada     2,761,584
29         New Hampshire     1,321,069
30            New Jersey     8,874,374
31            New Mexico     2,080,085
32              New York    19,594,330
33        North Carolina     9,750,405
34          North Dakota       704,925
35                  Ohio    11,560,380
36              Oklahoma     3,818,851
37                Oregon     3,900,343
38          Pennsylvania    12,758,729
39          Rhode Island     1,053,252
40        South Carolina     4,727,273
41          South Dakota       834,708
42             Tennessee     6,451,365
43                 Texas    26,092,033
44                  Utah     2,858,111
45               Vermont       626,358
46              Virginia     8,185,131
47            Washington     6,899,123
48         West Virginia     1,853,881
49             Wisconsin     5,724,692
50               Wyoming       575,251

In [ ]:
pd.set_option("display.max_columns", 80)